# Generated by Django 5.0.4 on 2024-04-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='job')),
                ('job_category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'job_category',
            },
        ),
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('url', models.URLField(unique=True)),
                ('company_description', models.TextField()),
                ('req_knowledge_skills_abilities', models.TextField()),
                ('education_experience', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.IntegerField(blank=True, null=True)),
                ('job_nature', models.CharField(choices=[('part time', 'Part Time'), ('full time', 'Full Time')], max_length=9)),
                ('salary_yearly_range', models.CharField(blank=True, max_length=100, null=True)),
                ('last_date_apply_application', models.DateField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.country')),
                ('company_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_details_category', to='backend.job_category')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_details_job_role', to='backend.job_category')),
            ],
            options={
                'db_table': 'company_details',
            },
        ),
        migrations.CreateModel(
            name='Job_apply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('passed_out_year', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='job_apply')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('company_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company_details')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.job_category')),
            ],
            options={
                'db_table': 'job_apply',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.country')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.AddField(
            model_name='company_details',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.state'),
        ),
    ]
