# Generated by Django 5.0.4 on 2024-04-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='company_category',
        ),
    ]
